# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies including devDependencies to build
RUN npm install

# Copy all source files
COPY . .

# Build the project
RUN npm run build

# Expose necessary port if needed (optional)

# Start the MCP server
CMD ["node", "build/index.js"]
